server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: http://81.70.55.81:8848
    gateway:
      routes:
        - id: user-service # 路由表示，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断线，判断请求是否符合规则
            - Path=/user/** # 路由断言，判断路径是否是以/user开头，如果是则符合
#          filters:
#            - AddRequestHeader=Truth, Itcast is freaking aowsome!
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
            - Before=2023-01-20T17:42:47.789+08:00[Asia/Shanghai]
      default-filters:
        - AddRequestHeader=Truth, Itcast is freaking aowsome!
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins: # 允许那些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "OPTONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否循序携带cookie
            maxAge: 360000 # 这次跨域检测的有效期